export const STATE_CHOICES = [
  ["AL", "Alabama"],
  ["AK", "Alaska"],
  ["AZ", "Arizona"],
  ["AR", "Arkansas"],
  ["CA", "California"],
  ["CO", "Colorado"],
  ["CT", "Connecticut"],
  ["DE", "Delaware"],
  ["DC", "District of Columbia"],
  ["FL", "Florida"],
  ["GA", "Georgia"],
  ["HI", "Hawaii"],
  ["ID", "Idaho"],
  ["IL", "Illinois"],
  ["IN", "Indiana"],
  ["IA", "Iowa"],
  ["KS", "Kansas"],
  ["KY", "Kentucky"],
  ["LA", "Louisiana"],
  ["ME", "Maine"],
  ["MD", "Maryland"],
  ["MA", "Massachusetts"],
  ["MI", "Michigan"],
  ["MN", "Minnesota"],
  ["MS", "Mississippi"],
  ["MO", "Missouri"],
  ["MT", "Montana"],
  ["NE", "Nebraska"],
  ["NV", "Nevada"],
  ["NH", "New Hampshire"],
  ["NJ", "New Jersey"],
  ["NM", "New Mexico"],
  ["NY", "New York"],
  ["NC", "North Carolina"],
  ["ND", "North Dakota"],
  ["OH", "Ohio"],
  ["OK", "Oklahoma"],
  ["OR", "Oregon"],
  ["PA", "Pennsylvania"],
  ["RI", "Rhode Island"],
  ["SC", "South Carolina"],
  ["SD", "South Dakota"],
  ["TN", "Tennessee"],
  ["TX", "Texas"],
  ["UT", "Utah"],
  ["VT", "Vermont"],
  ["VA", "Virginia"],
  ["WA", "Washington"],
  ["WV", "West Virginia"],
  ["WI", "Wisconsin"],
  ["WY", "Wyoming"],
];

export const PROPERTY_TYPES = [
  "Commercial",
  "Office",
  "Shop",
  "House",
  "Residential",
  "Apartment",
  "Condo",
  "Multi_Family_Home",
  "Single_Family_Home",
  "Studio",
  "Villa",
  "Town_House",
];

export const PROPERTY_FEATURES = [
  "Single_Family_Residence",
  "Furnished",
  "New_Construction",
  "Air_Conditioning",
  "Central_AC",
  // "Central_Air_Heat",
  "Alarm_Monitoring_Services",
  "Smart_Door_Locks",
  "Smart_Thermostat",
  "Backyard",
  "Private_Backyard",
  "Large_Backyard",
  "Balcony",
  // "Generous_Patios",
  // "Barbeque",
  "Sprinkler_System",
  "Car_Port",
  "Garage",
  // "Attached_Garage_Parking",
  "Covered_Parking",
  "Off_Street_Parking",
  // "Gated_Parking",
  "Gated_Off_Street_Parking",
  // "Laundry",
  "In_Unit_Laundry",
  // "Separate_Laundry_Room",
  // "Dryer",
  "Fireplace",
  // "Vaulted_Master_Bedroom",
  "Walk_In_Closets",
  // "Utility_Room",
  "Hardwood_Flooring",
  // "Engineered_Hardwood_Flooring",
  "Luxury_Vinyl_Tile_Flooring",
  // "Solid_Surface_Flooring",
  "Carpet",
  "Stained_Concrete_Flooring",
  "Quartz_Countertops",
  "Granite_Countertops",
  "Shaker_Style_Cabinets",
  "Stainless_Steel_Appliances",
  // "Dishwasher",
  // "Refrigerator",
  // "Microwave",
  // "Oven",
  // "Tankless_Water_Heater",
  // "Gym",
  "Lawn_Care",
  "Yard_Maintenance",
  "Walking_Distance",
  "Security_Cameras",
  "Duplex",
];

export const PROPERTY_FEATURE_NORMALIZATION = {
  Statinless_Steel: "Stainless_Steel_Appliances",
  Stainless_Stell: "Stainless_Steel_Appliances",
  Stainless_Steel_Appliances: "Stainless_Steel_Appliances",
  Stainless_Steel_Appliances: "Stainless_Steel_Appliances",
};

export function friendlyLabel(value) {
  return String(value || "")
    .replace(/_/g, " ")
    .replace(/-/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

export function friendlyFeatureLabel(value) {
  const raw = String(value || "").trim();
  const normalized = PROPERTY_FEATURE_NORMALIZATION[raw] || raw;
  return normalized.replace(/_/g, " ").replace(/-/g, " ").trim();
}
